//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lamb_Ji_DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Actualite
    {
        public int actuID { get; set; }
        [Required(ErrorMessage = "Le Titre est requis!")]
        [DisplayName("Titre de l'Actu")]
        public string actuTitre { get; set; }
        [Required(ErrorMessage = "Le nom est requis!")]
        [DisplayName("Contenu")]
        public string actuTexte { get; set; }
        [DisplayName("Image de l'Actu")]
        public string actuImgUrl { get; set; }
        [Required(ErrorMessage = "Le nom est requis!")]
        [DisplayName("Nom de l'Actu")]
        public string actuNom { get; set; }
        [DisplayName("Date de publication")]
        public Nullable<System.DateTime> actuDate { get; set; }
    }
}
