//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lamb_Ji_DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Arbitre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arbitre()
        {
            this.Combats = new HashSet<Combat>();
        }
    
        public int ArbitreID { get; set; }
        [Required(ErrorMessage = "Le nom est requis!")]
        [DisplayName("Nom de l'Arbitre")]
        public string ArbitreName { get; set; }
        [Required(ErrorMessage = "L'email est requis!")]
        [DisplayName("Email")]
        public string ArbitreEmail { get; set; }
        public Nullable<System.DateTime> ArbitreDateNaissance { get; set; }
        public string imageUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Combat> Combats { get; set; }
    }
}
