//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lamb_Ji_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Combat()
        {
            this.Arbitres = new HashSet<Arbitre>();
            this.Affiches = new HashSet<Affiche>();
        }
    
        public int CombatID { get; set; }
        public string Combat_Description { get; set; }
        public int TypeLutteID { get; set; }
        public int CategorieID { get; set; }
        public int StadeID { get; set; }
        public string Combat_Etat { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Stade Stade { get; set; }
        public virtual TypeLutte TypeLutte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arbitre> Arbitres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Affiche> Affiches { get; set; }
    }
}
